import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createDecipheriv } from 'node:crypto';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { unzipSync, strFromU8 } from 'fflate';
import WebSocket from 'ws';
import { openStore } from '../server/store.mjs';
import { createPanel } from '../server/index.mjs';
import { hashPassword } from '../server/security.mjs';
import { clientAddress } from '../server/licensing.mjs';
const origin = 'https://panel.example.test';
const fingerprint = 'a'.repeat(64);
async function fixture(t) {
 const dir = await mkdtemp(join(tmpdir(), 'fiveiso-license-'));
 const resourceTemplate = join(dir, 'template.json');
 await writeFile(resourceTemplate, JSON.stringify({ files: { 'fiveiso/fxmanifest.lua': "game 'gta5'", 'fiveiso/database-config.lua': 'Config = {}' }, payload: { secretLogic: 'not shipped as plaintext' } }));
 const db = openStore(':memory:');
 for (const role of ['owner','admin','viewer']) db.prepare('INSERT INTO users VALUES(?,?,?)').run(role,hashPassword('test-password-123'),role);
 const app = createPanel({ db, origin, resourceTemplate });
 app.server.listen(0,'127.0.0.1'); await once(app.server,'listening');
 t.after(async()=>{app.dispose();app.server.closeAllConnections();await new Promise(r=>app.server.close(r));db.close();await rm(dir,{recursive:true,force:true});});
 const base = `http://127.0.0.1:${app.server.address().port}`;
 const request = async (path, body, cookie='', headers={}) => fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
 const login = async role => (await request('/login',{username:role,password:'test-password-123'})).headers.get('set-cookie').split(';')[0];
 const owner=await login('owner'), manager=await login('admin'), viewer=await login('viewer');
 const server=await (await request('/servers',{name:'Licensed',region:'TR',framework:'QBCore'},owner)).json();
 return {db,request,owner,manager,viewer,server,base};
}
async function install(f) {
 const path=`/servers/${f.server.id}`;
 assert.equal((await f.request(path+'/license',{action:'create'},f.manager)).status,200);
 const download = await f.request(path+'/package',undefined,f.manager);
 assert.equal(download.status,200);assert.match(download.headers.get('cache-control'),/no-store/);
 const zip=unzipSync(new Uint8Array(await download.arrayBuffer()));
 const config=JSON.parse(strFromU8(zip['fiveiso/license.json']));
 const headers={'X-FiveISO-Server':config.serverId,Authorization:'Bearer '+config.token,'X-FiveISO-Instance':fingerprint};
 return {path,zip,config,headers};
}
test('package is tenant-isolated; encrypted payload key is released only after binding; all transports enforce it',async t=>{
 const f=await fixture(t), {request,db,server,owner,viewer,base}=f;
 const path=`/servers/${server.id}`;
 assert.equal((await request(path+'/license',{action:'create'},viewer)).status,403);
 assert.equal((await request(path+'/license',{action:'create'},'',{})).status,401);
 const {zip,config,headers}=await install(f);
 assert.equal((await request(path+'/license',{action:'create'},f.manager)).status,409);
 assert.equal((await request(path+'/package',undefined,viewer)).status,403);
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',headers)).status,403);
 assert.equal((await request('/license/activate',{packageId:'wrong'},'',headers)).status,403);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',{...headers,Authorization:'Bearer wrong'})).status,401);
 const activation=await request('/license/activate',{packageId:config.packageId},'',headers);
 assert.equal(activation.status,200);
 const grant=await activation.json();assert.equal(grant.ok,true);
 const data=Buffer.from(strFromU8(zip['fiveiso/runtime.fiso']),'base64');
 assert.equal(data.subarray(0,5).toString(),'FISO1');
 assert(!strFromU8(zip['fiveiso/runtime.fiso']).includes('secretLogic'));
 const decrypt=(blob,key=grant.key)=>{const d=createDecipheriv('aes-256-gcm',Buffer.from(key,'base64'),blob.subarray(5,17));d.setAAD(Buffer.from(config.packageId));d.setAuthTag(blob.subarray(17,33));return Buffer.concat([d.update(blob.subarray(33)),d.final()]).toString();};
 assert.deepEqual(JSON.parse(decrypt(data)),{secretLogic:'not shipped as plaintext'});
 const tampered=Buffer.from(data);tampered[40]^=1;assert.throws(()=>decrypt(tampered));
 assert.throws(()=>decrypt(data,Buffer.alloc(32).toString('base64')));
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',headers)).status,200);
 for(const route of ['/agent/heartbeat','/agent/screens','/agent/inventory-image'])
  assert.equal((await request(route,{},'',{...headers,'X-FiveISO-Instance':'b'.repeat(64)})).status,403);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',{...headers,'X-FiveISO-Instance':'b'.repeat(64)})).status,409);
 const ws=new WebSocket(base.replace('http:','ws:')+'/api/agent/stream',{headers:{...headers,'X-FiveISO-Instance':'wrong'}});
 await assert.rejects(once(ws,'open'),/401/);
 db.prepare('UPDATE resource_licenses SET bound_ip=? WHERE server_id=?').run('203.0.113.99',server.id);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,409);
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',headers)).status,403);
 db.prepare('UPDATE resource_licenses SET bound_ip=?,lease_until=0 WHERE server_id=?').run('127.0.0.1',server.id);
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',headers)).status,403);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,200);
 const socket=new WebSocket(base.replace('http:','ws:')+'/api/agent/stream',{headers});await once(socket,'open');
 t.after(()=>socket.terminate());
 db.prepare("UPDATE tenants SET enabled=0 WHERE id='local'").run();
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,403);
 assert.equal((await request('/agent/screens',{},'',headers)).status,403);
 db.prepare("UPDATE tenants SET enabled=1,expires='2000-01-01' WHERE id='local'").run();
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,403);
 db.prepare("UPDATE tenants SET expires=NULL WHERE id='local'").run();
 db.prepare('INSERT INTO tenants(id,name,features) VALUES(?,?,?)').run('other','Other','[]');
 await request('/owner/assign-server',{serverId:server.id,tenantId:'other'},owner);
 assert.equal((await request(path+'/package',undefined,f.manager)).status,403);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,403);
 assert.equal((await request(path+'/package',undefined,owner)).status,404);
 assert.equal((await request('/owner/delete',{kind:'tenant',id:'local'},owner)).status,200);
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',headers)).status,403);
 assert.equal((await request('/license/activate',{packageId:config.packageId},'',headers)).status,403);
});
test('revoking tombstones old credentials; a new package gets a new key and binding',async t=>{
 const f=await fixture(t), {request,manager,db}=f;
 const first=await install(f);
 await request('/license/activate',{packageId:first.config.packageId},'',first.headers);
 assert.equal((await request(first.path+'/license',{action:'revoke'},manager)).status,200);
 assert.equal(db.prepare('SELECT archive FROM resource_licenses').get().archive,null);
 assert.equal((await request('/license/activate',{packageId:first.config.packageId},'',first.headers)).status,401);
 assert.equal((await request(first.path+'/package',undefined,manager)).status,404);
 const second=await install(f);
 assert.notEqual(first.config.packageId,second.config.packageId);assert.notEqual(first.config.token,second.config.token);
 assert.equal((await request('/license/activate',{packageId:second.config.packageId},'',{...second.headers,'X-FiveISO-Instance':'b'.repeat(64)})).status,200);
 assert.equal((await request('/agent/heartbeat',{pollOnly:true},'',first.headers)).status,401);
});
test('client IP trusts only an explicitly configured local reverse proxy',()=>{
 const req=(address,forwarded)=>({socket:{remoteAddress:address},headers:{'x-real-ip':forwarded}});
 assert.equal(clientAddress(req('198.51.100.2','203.0.113.2'),true),'198.51.100.2');
 assert.equal(clientAddress(req('127.0.0.1','203.0.113.2'),false),'127.0.0.1');
 assert.equal(clientAddress(req('127.0.0.1','203.0.113.2'),true),'203.0.113.2');
 assert.equal(clientAddress(req('::ffff:192.0.2.2')), '192.0.2.2');
 assert.throws(()=>clientAddress(req('127.0.0.1','not-an-ip'),true));
});
